name: Docker Build and Push

on:
    release:
      types:
        - released
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: stable_docker
    permissions:
        id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Checkout code #clones repository
        uses: actions/checkout@v3 #the action that is used to checkout the code

      - name: Login to DockerHub 
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2 #the action that is used to build and push any image
        with:
            context: ./image_files/software-base/
            file: ./image_files/software-base/Dockerfile
            push: true
            tags: guorbit/orbit-software-base:latest