name: Docker Build and Push

on:
  push:
    branches: [ "development" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "development" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
        id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Checkout code #clones repository
        uses: actions/checkout@v3 #the action that is used to checkout the code

      - name: Login to DockerHub 
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t guorbit/orbit-software-base:latest .
        working-directory: .\image_files\software-base\Dockerfile
        
      - name: Tag Docker Image
        run: docker tag guorbit/orbit-software-base:latest guorbit/orbit-software-base:py3.10-tf2.13-utils0.1

      - name: Push Docker Image
        run: docker push guorbit/orbit-software-base:latest 