name: Docker Build and Push

on:
  release:
    types:
      - released

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: stable_docker
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set release tag
        id: vars
        run: echo "::set-output name=tag::${{ github.event.release.tag_name || 'latest' }}"

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./image_files/land-seg/
          file: ./image_files/land-seg/Dockerfile
          push: true
          tags: |
            guorbit/orbit-software-landseg:latest
            guorbit/orbit-software-landseg:${{ steps.vars.outputs.tag }}
