name: stable pypi build push

on:
    push:
      branches: [ "development" ]
    pull_request:
      branches: [ "development" ]

jobs:
    build-push-pypi:
        runs-on: ubuntu-latest
        environment: stable_pypi
        steps:
            - uses: actions/checkout@v3
            - name: Setup python 3.10
              uses: actions/setup-python@v4
              with:
                  python-version: 3.10
            - name: Build source and wheel
              run: |
                  python -m pip install --upgrade build twine
                  python -m build
                  twine check --strict dist/*
            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                    user: __token__
                    password: ${{ secrets.PYPI_TEST }}

            
              
            